# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.g_folder = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_folder.sizePolicy().hasHeightForWidth())
        self.g_folder.setSizePolicy(sizePolicy)
        self.g_folder.setObjectName("g_folder")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.g_folder)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folderLine = QtWidgets.QLineEdit(self.g_folder)
        self.folderLine.setObjectName("folderLine")
        self.horizontalLayout.addWidget(self.folderLine)
        self.browseButton = QtWidgets.QPushButton(self.g_folder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.verticalLayout_3.addWidget(self.g_folder)
        self.g_imageView = QtWidgets.QGraphicsView(self.groupBox)
        self.g_imageView.setObjectName("g_imageView")
        self.verticalLayout_3.addWidget(self.g_imageView)
        self.imageControls = QtWidgets.QGroupBox(self.groupBox)
        self.imageControls.setEnabled(False)
        self.imageControls.setObjectName("imageControls")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.imageControls)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.imageControls)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.imageControls)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.spinBox = QtWidgets.QSpinBox(self.imageControls)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.label = QtWidgets.QLabel(self.imageControls)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.checkBox = QtWidgets.QCheckBox(self.imageControls)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.pushButton_4 = QtWidgets.QPushButton(self.imageControls)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_3.addWidget(self.imageControls)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.file_struct = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_struct.sizePolicy().hasHeightForWidth())
        self.file_struct.setSizePolicy(sizePolicy)
        self.file_struct.setObjectName("file_struct")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.file_struct)
        self.verticalLayout.setObjectName("verticalLayout")
        self.g_f_gps = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_gps.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_gps.sizePolicy().hasHeightForWidth())
        self.g_f_gps.setSizePolicy(sizePolicy)
        self.g_f_gps.setCheckable(False)
        self.g_f_gps.setObjectName("g_f_gps")
        self.verticalLayout.addWidget(self.g_f_gps)
        self.g_f_lms_front = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_lms_front.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_lms_front.sizePolicy().hasHeightForWidth())
        self.g_f_lms_front.setSizePolicy(sizePolicy)
        self.g_f_lms_front.setCheckable(False)
        self.g_f_lms_front.setObjectName("g_f_lms_front")
        self.verticalLayout.addWidget(self.g_f_lms_front)
        self.g_f_models = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_models.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_models.sizePolicy().hasHeightForWidth())
        self.g_f_models.setSizePolicy(sizePolicy)
        self.g_f_models.setCheckable(False)
        self.g_f_models.setObjectName("g_f_models")
        self.verticalLayout.addWidget(self.g_f_models)
        self.g_f_processed = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_processed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_processed.sizePolicy().hasHeightForWidth())
        self.g_f_processed.setSizePolicy(sizePolicy)
        self.g_f_processed.setCheckable(False)
        self.g_f_processed.setObjectName("g_f_processed")
        self.verticalLayout.addWidget(self.g_f_processed)
        self.g_f_stereo = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_stereo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_stereo.sizePolicy().hasHeightForWidth())
        self.g_f_stereo.setSizePolicy(sizePolicy)
        self.g_f_stereo.setCheckable(False)
        self.g_f_stereo.setObjectName("g_f_stereo")
        self.verticalLayout.addWidget(self.g_f_stereo)
        self.g_f_left = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_left.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_left.sizePolicy().hasHeightForWidth())
        self.g_f_left.setSizePolicy(sizePolicy)
        self.g_f_left.setCheckable(False)
        self.g_f_left.setObjectName("g_f_left")
        self.verticalLayout.addWidget(self.g_f_left)
        self.g_f_centre = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_centre.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_centre.sizePolicy().hasHeightForWidth())
        self.g_f_centre.setSizePolicy(sizePolicy)
        self.g_f_centre.setCheckable(False)
        self.g_f_centre.setObjectName("g_f_centre")
        self.verticalLayout.addWidget(self.g_f_centre)
        self.g_f_right = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_right.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_right.sizePolicy().hasHeightForWidth())
        self.g_f_right.setSizePolicy(sizePolicy)
        self.g_f_right.setCheckable(False)
        self.g_f_right.setObjectName("g_f_right")
        self.verticalLayout.addWidget(self.g_f_right)
        self.g_f_lmsTime = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_lmsTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_lmsTime.sizePolicy().hasHeightForWidth())
        self.g_f_lmsTime.setSizePolicy(sizePolicy)
        self.g_f_lmsTime.setCheckable(False)
        self.g_f_lmsTime.setObjectName("g_f_lmsTime")
        self.verticalLayout.addWidget(self.g_f_lmsTime)
        self.g_f_stereoTime = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_stereoTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_f_stereoTime.sizePolicy().hasHeightForWidth())
        self.g_f_stereoTime.setSizePolicy(sizePolicy)
        self.g_f_stereoTime.setCheckable(False)
        self.g_f_stereoTime.setObjectName("g_f_stereoTime")
        self.verticalLayout.addWidget(self.g_f_stereoTime)
        self.g_f_good = QtWidgets.QCheckBox(self.file_struct)
        self.g_f_good.setEnabled(True)
        self.g_f_good.setCheckable(False)
        self.g_f_good.setObjectName("g_f_good")
        self.verticalLayout.addWidget(self.g_f_good)
        self.verticalLayout_4.addWidget(self.file_struct)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.g_folder.setTitle(_translate("MainWindow", "Dataset Folder"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.imageControls.setTitle(_translate("MainWindow", "Image Controls"))
        self.pushButton_2.setText(_translate("MainWindow", "Previous"))
        self.pushButton_3.setText(_translate("MainWindow", "Run"))
        self.label.setText(_translate("MainWindow", "Run delay (ms)"))
        self.checkBox.setText(_translate("MainWindow", "View Original"))
        self.pushButton_4.setText(_translate("MainWindow", "Next"))
        self.file_struct.setTitle(_translate("MainWindow", "File structure check"))
        self.g_f_gps.setText(_translate("MainWindow", "gps"))
        self.g_f_lms_front.setText(_translate("MainWindow", "lms_front"))
        self.g_f_models.setText(_translate("MainWindow", "Models"))
        self.g_f_processed.setText(_translate("MainWindow", "processed"))
        self.g_f_stereo.setText(_translate("MainWindow", "stereo"))
        self.g_f_left.setText(_translate("MainWindow", "→ Left"))
        self.g_f_centre.setText(_translate("MainWindow", "→ Centre"))
        self.g_f_right.setText(_translate("MainWindow", "→ Right"))
        self.g_f_lmsTime.setText(_translate("MainWindow", "lms_front.timestamps"))
        self.g_f_stereoTime.setText(_translate("MainWindow", "stereo.timestamps"))
        self.g_f_good.setText(_translate("MainWindow", "Folder structure good!"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Image List"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Thing 1"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Thing 2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
